# Generated by Django 4.1.5 on 2023-01-17 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trainer_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_category', models.CharField(max_length=4)),
                ('sportsmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.armwrestler')),
            ],
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
