# Generated by Django 4.1.5 on 2023-01-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tournamentregistration_delete_tournament'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentRegistration',
            new_name='TournamentPreRegistrationModel',
        ),
    ]
