# Generated by Django 4.1.5 on 2023-01-17 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_tournamentregistration_tournamentpreregistrationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('competitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournamentpreregistrationmodel')),
            ],
        ),
    ]
