# Generated by Django 4.1.5 on 2023-01-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpreregistrationmodel',
            name='date',
            field=models.ManyToManyField(to='main.tournaments'),
        ),
    ]
