# Generated by Django 4.1.5 on 2023-01-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tournamentpreregistrationmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournaments',
            name='competitors',
        ),
    ]
