# Generated by Django 4.1.5 on 2023-01-17 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_tournaments_competitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentpreregistrationmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='tournamentpreregistrationmodel',
            name='tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.tournaments'),
        ),
    ]
