# Generated by Django 4.1.5 on 2023-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_tournamentpreregistrationmodel_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentpreregistrationmodel',
            name='tour',
        ),
        migrations.AddField(
            model_name='tournamentpreregistrationmodel',
            name='date',
            field=models.ManyToManyField(to='main.tournaments'),
        ),
    ]
