# Generated by Django 4.1.4 on 2023-01-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_tournamentpreregistrationmodel_tour_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tournamentpreregistrationmodel',
        #     name='date',
        # ),
        migrations.AddField(
            model_name='tournamentpreregistrationmodel',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.tournaments'),
        ),
    ]
