# Generated by Django 4.1.6 on 2023-02-05 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armwrestler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(67)])),
                ('weight_category', models.CharField(default='60', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
                ('hand', models.CharField(default='left', max_length=5)),
                ('baba', models.CharField(default='555', max_length=66)),
                ('title', models.CharField(max_length=100)),
                ('sportsmens', models.ManyToManyField(to='main.armwrestler')),
            ],
        ),
    ]
