# Generated by Django 4.1.6 on 2023-02-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='sex',
            field=models.CharField(choices=[('men', 'Мужчина'), ('women', 'Женщина')], default='men', max_length=5),
        ),
    ]
