# Generated by Django 4.1.6 on 2023-02-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_competition_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='baba',
        ),
        migrations.AlterField(
            model_name='competition',
            name='category',
            field=models.CharField(choices=[('50', '50'), ('55', '55'), ('60', '60'), ('65', '65'), ('70', '70'), ('75', '75'), ('80', '80'), ('85', '85'), ('90', '90'), ('100', '100'), ('110', '110'), ('+110', '+110'), ('+80', '+80')], default='50', max_length=5),
        ),
        migrations.AlterField(
            model_name='competition',
            name='hand',
            field=models.CharField(choices=[('left', 'сетка по левым рукам'), ('r', 'сетка по правым рукам')], default='left', max_length=5),
        ),
    ]
