# Generated by Django 4.1.6 on 2023-02-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_allcompetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='armwrestler',
            name='grade',
            field=models.CharField(default='б/р', max_length=4),
        ),
        migrations.AddField(
            model_name='armwrestler',
            name='sex',
            field=models.CharField(default='m', max_length=2),
        ),
    ]
