# Generated by Django 4.1.6 on 2023-02-26 03:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_armwrestler_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_competition', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=4)),
                ('hand', models.CharField(max_length=5)),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sportsmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.armwrestler')),
            ],
        ),
    ]
