# Generated by Django 4.1.6 on 2023-02-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_allresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='allresults',
            name='sex',
            field=models.CharField(default='m', max_length=4),
        ),
    ]
