# Generated by Django 4.1.6 on 2023-02-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_allresults_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allresults',
            name='sportsmen',
            field=models.CharField(max_length=100),
        ),
    ]
