# Generated by Django 4.1.6 on 2023-02-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_allresults_sportsmen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcompetition',
            name='content',
        ),
    ]
