# Generated by Django 4.1.6 on 2023-02-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_allcompetition_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsmenRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allcompetition')),
                ('sportsmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.armwrestler')),
            ],
        ),
    ]
