# Generated by Django 4.1.7 on 2023-03-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_protocol_delete_competition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllResults',
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
