# Generated by Django 4.1.7 on 2023-03-15 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_allresults_delete_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.CharField(max_length=5)),
                ('place', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allcompetition')),
                ('sportsmen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.armwrestler')),
            ],
        ),
    ]
