# Generated by Django 4.1.7 on 2023-03-18 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_allresults_hand_allresults_left_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allresults',
            old_name='left',
            new_name='left_place',
        ),
        migrations.RenameField(
            model_name='allresults',
            old_name='right',
            new_name='right_place',
        ),
        migrations.RenameField(
            model_name='allresults',
            old_name='place',
            new_name='sum_place',
        ),
        migrations.AddField(
            model_name='allresults',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='allresults',
            name='points_left',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='allresults',
            name='points_right',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
