# Generated by Django 4.1.7 on 2023-03-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_left_allresults_left_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allresults',
            name='weight_cat',
            field=models.CharField(default='60', max_length=4),
        ),
    ]
