# Generated by Django 4.1.6 on 2023-03-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_allresults_weight_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armwrestler',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
