# Generated by Django 4.1.7 on 2023-03-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_armwrestler_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='allresults',
            name='weight_actual',
            field=models.CharField(default='60', max_length=4),
        ),
        migrations.AlterField(
            model_name='armwrestler',
            name='grade',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='armwrestler',
            name='sex',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='armwrestler',
            name='team',
            field=models.CharField(max_length=54),
        ),
        migrations.AlterField(
            model_name='armwrestler',
            name='weight_category',
            field=models.CharField(max_length=4),
        ),
    ]
