# Generated by Django 4.1.6 on 2023-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_armwrestler_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='armwrestler',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='armwrestler',
            name='sex',
            field=models.CharField(max_length=2),
        ),
    ]
